### ISSUE TITLE
modal solver bug

### ISSUE THREAD

**Issue by bgpantojar** [NumSoftware/Amaru.jl#38]
Hello,

I just tried to update the solver for modal analysis. Unfortunately, there is a bug I could not solved. The problem happens when the K matrix is being mount in [mount_K()](https://github.com/NumSoftware/Amaru.jl/blob/1363e9f928a44bec5a73c9a4a1972d0abba910f9/src/mech/mech-solver.jl#L4) function. What I think is the problem in the computation of ndofs comming from [configure_dofs!()](https://github.com/NumSoftware/Amaru.jl/blob/1363e9f928a44bec5a73c9a4a1972d0abba910f9/src/mech/modal-solver.jl#L132). See the next image. 

![Screenshot from 2022-09-13 17-39-24](https://user-images.githubusercontent.com/35929939/189947585-a3035d32-180e-4e7e-9d17-bcd8ac9fba72.png)

This problem might be happening as I modified the line where active elements are filtered [active elements](https://github.com/NumSoftware/Amaru.jl/blob/1363e9f928a44bec5a73c9a4a1972d0abba910f9/src/mech/modal-solver.jl#L163). I did this because when running the input file an error was issued with filter() function not defined.

Please find the example [here](https://u.pcloud.link/publink/show?code=kZ3d5hVZFEemFbM0qGF9mJKftuHVDz6BlmSV) if you have the time to check it out.

I have just pushed the modifications to the modal-solver.jl

Best,
Bryan

**Comment by RaulDurand** [comment]
I beliave there is no need to create a `mod_stage_solver!` function, since the modal solver doesn't run through stages. Thus, the function `mod_solve!(model::Model, bcs::Array; nmods::Int=5, rayleigh=false, save=true, quiet=false)` should be enough. However, I did not test this function jet.

**Comment by bgpantojar** [comment]
Agree. Although my first try was like that and did not work either (same problem presented).

**Comment by RaulDurand** [comment]
The problem seems to be when trying to mount the sparse matrix.

![image](https://user-images.githubusercontent.com/8837321/189972701-45bb5648-7db5-432f-93fb-fab6f7c2c1c6.png)

![image](https://user-images.githubusercontent.com/8837321/189972504-df29ad4a-f11d-4539-a081-512ff85d2990.png)

**Comment by RaulDurand** [comment]
I found an error in mod_solver! when creating a copy of the model with bulk elements only. I'll fix it it ASAP.

**Comment by bgpantojar** [comment]
Yes. In the sparse matrix the number of of dofs did not match. Make sense
that when copying the bulk elements it is not done properly.

**Comment by RaulDurand** [comment]
I reverted your last commit and fixed the problem with mod_solver .
I suggest pushing to the repository once changes leave the code in a working state.
See below your updated script. Please verify the results since some parts of the function have changed, especially the lines that filter eigenvalues and eigenvectors.
I am closing by now but feel free to open new issues on this matter.

```
using Amaru

mesh = Mesh("m1.vtk", reorder=true)
tag!(mesh.elems[:solids], "solids")
# Model definition

materials = [
    "solids" => ElasticSolid(E=30e6, nu=0.2, rho=24.0)
]
smooth!(mesh, quiet=true)

model = Model(mesh, materials)

# Finite element modeling
bcs = [
    :(z==0)   => NodeBC(ux=0, uy=0, uz=0),
]

mod_solve!(model, bcs, nmods=10)
```

**Comment by RaulDurand** [comment]
fixed
