### ISSUE TITLE
ElasticSolid class bug

### ISSUE THREAD

**Issue by bgpantojar** [NumSoftware/Amaru.jl#39]
Hello,

I just build Amaru in Julia 1.9.2 and tried to run a modal analysis. It raised an error related to the ElasticSolid class as shown in the image (Same when just trying to call that class manually).

![amaru_bug](https://github.com/NumSoftware/Amaru.jl/assets/35929939/cbcb17e6-6298-4f2e-ad6b-16260fd7bc02)

I am using the next script to run the modal analysis that it does work in julia 1.8.0 updating Amaru there.

![Screenshot from 2023-08-09 11-29-59](https://github.com/NumSoftware/Amaru.jl/assets/35929939/068a1557-89fa-4cfc-a104-60319e332d00)

does Amaru need an update to be used on Julia 1.9.2?

Thanks!

**Comment by RaulDurand** [comment]
Thanks for pointing this out.
The material input have changed recently to also specify the type of element in addition to the material model.
Please check the tests folder for the dynamic example dyn-solid.jl.
However, there is no test for modal analysis. I will work on it next week.

**Comment by RaulDurand** [comment]
I just updated the code and added a modal analysis.
