### ISSUE TITLE
The Document of Amaru should be precompiled and updated

### ISSUE THREAD

**Issue by pinkie-ljz** [NumSoftware/Amaru.jl#40]
As is indicated by the title. When I run some examples in the document, some errors occur. For example, the old function `mplot` is not defined and I do not find its definition in the source files. To get the newest document, I try to run make.jl in the folder /docs/ but fail to do it, see the attached figure.
![image](https://github.com/user-attachments/assets/e7e8abda-91c6-41ac-a18a-49150e63a3e7)
Any suggestions that can address this issue would be greatly appreciated！Thanks a lot.

**Comment by RaulDurand** [comment]
es, the examples are currently outdated. For instance, the old mplot function has been replaced with a significantly faster version that leverages Cairo. I am currently working on updating the documentation, and new examples will be rolled out gradually as they are added.

**Comment by pinkie-ljz** [comment]
> es, the examples are currently outdated. For instance, the old mplot function has been replaced with a significantly faster version that leverages Cairo. I am currently working on updating the documentation, and new examples will be rolled out gradually as they are added.

Thank you for your reply. I look forward to the release of the package with the latest version of documentation. Thank you for your work.
