### ISSUE TITLE
Derivatives in CEB bond model

### ISSUE THREAD

**Issue by kengwit** [NumSoftware/Amaru.jl#42]
Hi,

I was trying to run some bond slip model with the CEB model, but the convergence seems slow. I am looking at the derivatives here:

https://github.com/NumSoftware/Amaru.jl/blob/main/src/mech/mat/ceb-lsinterface.jl

```
function deriv(mat::CebLSJoint, state::CebLSJointState, sy::Float64)
    if sy==0.0
        s1_factor = 0.01
        sy = s1_factor*mat.s1   # to avoid undefined derivative
    end

    if sy<=mat.s1
        return mat.τmax/mat.s1*(sy/mat.s1)^(mat.α-1)
    elseif sy<mat.s2
        #return mat.ks/10000
        return 1.0
    elseif sy<mat.s3
        return -(mat.τmax-mat.τres)/(mat.s3-mat.s2)*((sy-mat.s2)/(mat.s3-mat.s2))^(mat.β-1)
    else
        return 1.0
        # return mat.ks/10000
    end
end
```

Are you missing the mat.α in front of:

```
        return mat.τmax/mat.s1*(sy/mat.s1)^(mat.α-1)
```

and also missing the mat.β in front of:

```
        return -(mat.τmax-mat.τres)/(mat.s3-mat.s2)*((sy-mat.s2)/(mat.s3-mat.s2))^(mat.β-1)
```

These should just be obtained by taking the derivative of the expressions in ```function Tau(mat::CebLSJoint, sy::Float64)```, correct?

Thank you.

**Comment by RaulDurand** [comment]
Hi @kengwit ,
Thanks for pointing this out. Actually this code was derived from a more complex one. 
In fact wrong derivatives will lead to slow convergence rates. I'll ckeck this carefully asap. Could you post a MWE?

**Comment by kengwit** [comment]
HI @RaulDurand 

I don't have a minimum working example. The slow convergence might be due to something else, e.g., a modeling error on my part, and I was just checking the code to understand what is going on - that's when I saw the derivatives. I haven't revisited the problem since I encountered the issue.

I guess if you need a MWE, you could take the 1 element test that I set up earlier and change the linear interface to the CEB interface and check the convergence. I don't know what one needs to do to print the convergence on the screen - I am actually not familiar with the Julia programming language at all.

**Comment by RaulDurand** [comment]
I fixed the derivatives in both models and in fact I found a reduction in the number of increments in the ceb.jl test.
Please let me know if this works for you.

**Comment by kengwit** [comment]
Thank you.
